# .github/workflows/docker-build.yml

name: Docker Build and Push to GHCR # 名前を少し変更 (任意)

on:
  push:
    branches: [ main ]
  # pull_request時はビルドのみにしたい場合、トリガーを分けるか条件分岐が必要だが、
  # 今回はシンプルに push 時のみプッシュするように変更
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-push: # ジョブIDも変更 (任意)
    runs-on: ubuntu-latest

    # ★★★ GITHUB_TOKEN に書き込み権限を付与 ★★★
    permissions:
      contents: read # コードの読み取り権限 (checkoutに必要)
      packages: write # GHCRへの書き込み権限 (pushに必要)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ★★★ GHCRへのログインステップを追加 ★★★
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # ワークフローを実行したユーザー名
          password: ${{ secrets.GITHUB_TOKEN }} # 自動的に生成されるトークン

      # docker/build-push-action の設定を修正
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # ★★★ push: true に変更 ★★★
          push: true
          tags: ghcr.io/kagetora610/my-next-app:latest # ★ご自身のユーザー名/リポジトリ名に要変更★
          cache-from: type=gha
          cache-to: type=gha,mode=max